In [4]:
# Create a CSV file containing product names and prices.
# Read the data using Pandas. 
# Use NumPy to calculate the average price. 
# Write a function to identify products priced above the average and display them
import pandas as pd
import numpy as np
df=pd.read_csv("products.csv")
df

      Product  Price
0      Laptop  55000
1       Mouse    800
2    Keyboard   1500
3     Monitor  12000
4  Headphones   2500
5     Printer   9000
6      Tablet  30000
7     Speaker   4000
8      Webcam   3500
9     Charger   1200

In [19]:
price=np.array(df["Price"])

average=np.mean(price)
print(avg)

11950.0

In [45]:
price=np.array(df["Price"])

average=np.mean(price)
print(average)
def predict():
    a=df[df["Price"]>average]
    return a["Product"]

11950.0

In [46]:
predict()

0     Laptop
3    Monitor
6     Tablet
Name: Product, dtype: object

11950.0
0     Laptop
3    Monitor
6     Tablet
Name: Product, dtype: object

In [51]:
# Read daily temperature data from a CSV file using Pandas. 
# Use NumPy to calculate the highest, lowest, and average temperatures.
# Write functions to classify each day as:


df2=pd.read_csv("temperature_data.csv")
df2

         Date  Temperature
0  2026-06-01           32
1  2026-06-02           38
2  2026-06-03           41
3  2026-06-04           29
4  2026-06-05           35
5  2026-06-06           44
6  2026-06-07           27

In [72]:
a=np.array(df2["Temperature"])
high=a.max()
cold=a.min()
moderate=a.mean()
print("Highest = ",high)
print("Cold = ",cold)    
print("moderate = ",moderate)

def calculate():
    if a<30:
        print("Cold")
    elif a<=40:
        print("Moderate")
    else:
        print("HOT")


df2['Report']=df2['Temperature'].apply(calculate)
print(df2)

Highest =  44
Cold =  27
moderate =  35.142857142857146

TypeError: calculate() takes 0 positional arguments but 1 was given

In [76]:
a=np.array(df2["Temperature"])
high=a.max()
cold=a.min()
moderate=a.mean()
print("Highest = ",high)
print("Cold = ",cold)    
print("moderate = ",moderate)

def calculate(a):
    if a<30:
        return "Cold"
    elif a<=40:
        return "Moderate"
    else:
        return "HOT"


df2['Report']=df2['Temperature'].apply(calculate)
print(df2)

Highest =  44
Cold =  27
moderate =  35.142857142857146
         Date  Temperature    Report
0  2026-06-01           32  Moderate
1  2026-06-02           38  Moderate
2  2026-06-03           41       HOT
3  2026-06-04           29      Cold
4  2026-06-05           35  Moderate
5  2026-06-06           44       HOT
6  2026-06-07           27      Cold